FROM python:3.11-bookworm
MAINTAINER kennywarwick

# Add application code
ADD app /app
WORKDIR app

# Install necessary packages
RUN apt-get update && apt-get install -y curl vim tree

# Install Python dependencies
RUN pip3 install -r requirements.txt

# Create a new user with a specific UID and switch to it
RUN groupadd -g 9001 myuser && \
    useradd -m -u 9001 -g myuser myuser
USER myuser

# Set the command to run the application
CMD ["python3"]